### ISSUE TITLE
Client can not connect to server- Unknown registry entries

### ISSUE THREAD

**Issue by professorparsnips** [moritz-htk/advanced-music-mod#1]
I installed this mod on my server, but am met with this exception each time I try to join without the client mod:
"[15:47:16] [Render thread/WARN]: Client disconnected with reason: Received 28 registry entries that are unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

advanced_music_mod"
Is this mod able to be run server-side only, as indicated on Modrinth?

Minecraft Java Edition 1.21.1 Fabric Server

**Comment by moritz-htk** [comment]
This mod isn't server-side only. You need to install it on both the client and the server. I think the compatibility on Modrinth should be set correctly, but I'm open to improvements.

**Comment by professorparsnips** [comment]
> This mod isn't server-side only. You need to install it on both the client and the server. I think the compatibility on Modrinth should be set correctly, but I'm open to improvements.

It shows as server or client, and having both as optional. I do think something might be tagged incorrectly or Modrinth just displays it incorrectly. Thanks for replying, appreciate it.

![musicmod](https://github.com/user-attachments/assets/1de09d12-098f-4cce-9862-7d387a07bf85)
![musicmod2](https://github.com/user-attachments/assets/965f86cb-af3a-459d-8672-0582fc592bae)
